version: '3'

services:
  flaskmyip:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile_home
    image: ${IMAGE_DOCKER_FLASK:-registry.tarcisio.me/home/flaskmyip:armv7l}
    container_name: flaskmyip
    env_file: ['.env']
    restart: unless-stopped
    ports: ['3002:3002']
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./templates:/srv/templates
      - ./datasets:/srv/datasets
      - ./keys_gpg:/srv/keys_gpg
      - ./run.py:/srv/run.py
      - ./clouds:/srv/clouds
      - ./lib:/srv/lib
    logging:
      driver: "json-file"
      options:
        max-size: "1000m"
    networks:
      ce_frontend:
        ipv4_address: 192.168.255.2
    dns:
      - 192.168.255.4

  cloudflared:
    container_name: cloudflared
    image: visibilityspots/cloudflared:latest
    restart: unless-stopped
    networks:
      ce_frontend:
        ipv4_address: 192.168.255.3

  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    restart: unless-stopped
    ports:
      - "8088:80/tcp"
      - "53:53/tcp"
      - "53:53/udp"
    volumes:
      - pihole:/etc/pihole
      - dnsmasq:/etc/dnsmasq.d
    environment:
      - ServerIP=192.168.255.4
      - DNS1=192.168.255.3#5054
      - DNS2=''
      - IPv6=false
      - TZ=America/Sao_Paulo
      - DNSMASQ_LISTENING=all
      - WEBPASSWORD=123.senha
    networks:
      ce_frontend:
        ipv4_address: 192.168.255.4
    dns:
      - 127.0.0.1

  ntp:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile_ntp
    image: ${IMAGE_DOCKER_NTP:-registry.tarcisio.me/home/ntp:armv7l}
    container_name: ntp
    restart: unless-stopped
    volumes:
      - ./docker/resolv.conf:/etc/resolv.conf
    ports:
      - 123:123/udp
    environment:
      - TZ=America/Sao_Paulo
      - NTP_SERVERS=time.cloudflare.com,time1.google.com,ntp1.aliyun.com
      - LOG_LEVEL=0
    networks:
      ce_frontend:
        ipv4_address: 192.168.255.88
    dns:
      - 192.168.255.4

  ftpd:
    image: stilliard/pure-ftpd
    restart: unless-stopped
    container_name: ftpd
    ports:
      - "21:21"
      - "30000-30099:30000-30099"
    volumes:
      - "./data/ftpd:/home/admin"
      - "ftp_passwd:/etc/pure-ftpd/passwd"
    environment:
      FTP_PASSIVE_PORTS: 30000:30099
      PUBLICHOST: "192.168.29.30"
      FTP_USER_NAME: admin
      FTP_USER_PASS: 123.senha
      FTP_USER_HOME: /home/admin
      PURE_FTPD_FLAGS: "-4"
      FTP_USER_HOME_PERMISSION: 777
    networks:
      ce_frontend:
        ipv4_address: 192.168.255.6
    dns:
      - 192.168.255.4


volumes:
  pihole:
  dnsmasq:
  ftp_passwd:

networks:
  ce_frontend:
    external: true
