# first, a bit about this container
# LABEL build_info="cturra/docker-ntp build-date:- ${BUILD_DATE}"
# LABEL maintainer="Chris Turra <cturra@gmail.com>"
# LABEL documentation="https://github.com/cturra/docker-ntp"

# FROM alpine:3.18
FROM arm32v7/alpine:3.18

RUN apk add --no-cache chrony python3 py3-pip tzdata
RUN cp /usr/share/zoneinfo/America/Sao_Paulo /etc/localtime
RUN echo "America/Sao_Paulo" > /etc/timezone

COPY docker/run_ntp.sh /srv/run.sh

EXPOSE 123/udp

HEALTHCHECK CMD chronyc tracking || exit 1
ENTRYPOINT [ "/bin/sh", "/srv/run.sh" ]
