# FROM alpine:3.18
FROM arm32v7/alpine:3.18

ENV AMB=prod

RUN apk add --no-cache rust cargo python3 py3-pip tzdata \
    && apk add --no-cache --virtual .build-deps gcc \
    musl-dev python3-dev libffi-dev openssl-dev make

RUN cp /usr/share/zoneinfo/America/Sao_Paulo /etc/localtime
RUN echo "America/Sao_Paulo" > /etc/timezone

COPY ./requirements.txt /srv/requirements.txt
RUN pip install -r /srv/requirements.txt

COPY ./lib /srv/lib
RUN rm -fr /srv/lib/__pycache__

COPY ./clouds /srv/clouds
RUN rm -fr /srv/clouds/__pycache__

COPY ./datasets /srv/datasets
COPY ./.env /srv/.env

COPY ./keys_gpg /srv/keys_gpg
COPY ./html /srv/html

RUN find /srv/keys_gpg/key_oci/ -type f -name "*public*.pem" -exec chmod 0664 {} \;
RUN find /srv/keys_gpg/key_oci/ -type f -name "*.pem" ! -name "*public*" -exec chmod 0600 {} \;

RUN rm -rf /var/lib/apk/* /tmp/* /var/tmp/*
RUN chown -R 1000:1000 /srv

WORKDIR /srv
COPY ./.env /srv/.env

RUN pip install routeros-api
RUN apk del .build-deps

ENTRYPOINT [ "python3", "run.py" ]
CMD [ "--prd" ]
